# Generated by Django 4.0.2 on 2022-02-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('url', models.URLField(verbose_name='URL:')),
                ('date', models.DateField(verbose_name='Data de Criação:')),
                ('commits', models.IntegerField(verbose_name='Commits:')),
                ('languages', models.CharField(max_length=200, verbose_name='Linguagens:')),
                ('last_commit', models.DateField(verbose_name='Data do último commit:')),
                ('status', models.CharField(max_length=100, verbose_name='Status:')),
            ],
            options={
                'verbose_name': 'repository',
                'verbose_name_plural': 'repositories',
                'ordering': ['-name'],
            },
        ),
    ]
