# Generated by Django 4.0.2 on 2022-03-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'respository',
                'verbose_name_plural': 'repositories',
                'db_table': 'repositories',
            },
        ),
    ]
