# Generated by Django 4.0.2 on 2022-03-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_repository_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='user',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
